extends RefCounted
class_name TacticalBattle

const EnemyData: Dictionary = {
	"firewall_sentinel": {
		"name": "Firewall Sentinel",
		"element": "stone",
		"level": 2,
		"stats": { "hp": 80, "atk": 14, "def": 22, "spd": 8 },
		"reward_xp": 25,
		"reward_scraps": 30,
		"reward_flag": "",
		"reward_key_item": "",
	},
	"bit_wraith": {
		"name": "Bit Wraith",
		"element": "shadow",
		"level": 4,
		"stats": { "hp": 55, "atk": 22, "def": 10, "spd": 20 },
		"reward_xp": 40,
		"reward_scraps": 50,
		"reward_flag": "",
		"reward_key_item": "",
	},
	"glitch_hydra": {
		"name": "Glitch Hydra",
		"element": "storm",
		"level": 7,
		"stats": { "hp": 75, "atk": 24, "def": 16, "spd": 18 },
		"reward_xp": 60,
		"reward_scraps": 80,
		"reward_flag": "",
		"reward_key_item": "",
	},
	"recursive_golem": {
		"name": "Recursive Golem",
		"element": "stone",
		"level": 10,
		"stats": { "hp": 120, "atk": 20, "def": 28, "spd": 6 },
		"reward_xp": 80,
		"reward_scraps": 120,
		"reward_flag": "recursive_golem_defeated",
		"reward_key_item": "",
	},
	"buffer_overflow": {
		"name": "Buffer Overflow",
		"element": "fire",
		"level": 3,
		"stats": { "hp": 90, "atk": 18, "def": 16, "spd": 14 },
		"reward_xp": 30,
		"reward_scraps": 40,
		"reward_flag": "",
		"reward_key_item": "",
	},
	"crypto_crab": {
		"name": "Crypto Crab",
		"element": "ice",
		"level": 5,
		"stats": { "hp": 85, "atk": 20, "def": 22, "spd": 12 },
		"reward_xp": 45,
		"reward_scraps": 60,
		"reward_flag": "",
		"reward_key_item": "",
	},
	"logic_bomb": {
		"name": "Logic Bomb",
		"element": "fire",
		"level": 8,
		"stats": { "hp": 70, "atk": 30, "def": 12, "spd": 24 },
		"reward_xp": 65,
		"reward_scraps": 90,
		"reward_flag": "",
		"reward_key_item": "",
	},
	"phishing_siren": {
		"name": "Phishing Siren",
		"element": "venom",
		"level": 6,
		"stats": { "hp": 80, "atk": 24, "def": 16, "spd": 20 },
		"reward_xp": 50,
		"reward_scraps": 70,
		"reward_flag": "",
		"reward_key_item": "",
	},
}
