extends RefCounted
## Authored compact campaign. Names and themes inherit the browser canon; spatial layouts/rules are new.
const ZONES = [
	{"id": "outer", "name": "Outer Grid", "color": "efac62", "entry": "field-locker", "path": "signal-approach", "gate": "firewall-span", "cache": "maintenance-cache", "boss": "overflow-vent", "boss_name": "Buffer Overflow", "pattern": ["slam", "ring"], "theme": "foundry", "story": "The outside relays still remember the Forge. Reconnect the failing span and reclaim its thermal core.", "reward": "Thermal core", "tip": "The Sentinel closes its shield. Let it slam, then punish its recovery."},
	{"id": "frozen", "name": "Frozen Cache", "color": "80dcea", "entry": "cold-archive", "path": "mute-channel", "gate": "thaw-junction", "cache": "frozen-vault", "boss": "memory-vault", "boss_name": "Memory Leak", "pattern": ["beam", "slam"], "theme": "ice", "story": "Memories were frozen to keep them safe. Now the ice is erasing the people inside them. Bring the archive back online.", "reward": "Memory core", "tip": "The beam locks its direction before firing. Move sideways, not down its length."},
	{"id": "storm", "name": "Storm Spine", "color": "baa4ff", "entry": "overclock-gantry", "path": "live-wire", "gate": "wire-fork", "cache": "capacitor-cache", "boss": "logic-core", "boss_name": "Stack Overflow", "pattern": ["fan", "beam"], "theme": "storm", "story": "The spine is overclocking itself to death. Reroute the conductors, then quiet the process driving the surge.", "reward": "Conductor core", "tip": "Gold circles mark three separate impacts. Find the gap before they discharge."},
	{"id": "admin", "name": "Admin Core", "color": "eab8e5", "entry": "mirror-vestibule", "path": "recursive-gate", "gate": "cold-lanterns", "cache": "admin-vault", "boss": "protocol-throne", "boss_name": "Mirror Admin", "pattern": ["ring", "beam", "fan"], "theme": "void", "story": "The administrator calls it a reset. Felix calls it forgetting everyone. Wake the cold lanterns and take back the last core.", "reward": "Protocol core", "tip": "A ring attack has a safe center. Get close or leave the whole marked ring."}
]
const ROOMS = {
	"forge": {"id": "forge", "name": "The Forge", "zone": "home", "role": "forge", "layout": "forge", "exits": [], "enemies": [], "relays": [], "hazards": [], "lore": "Felix: The Forge was never a weapon. It was where damaged processes came to become something else.\n\nFour sectors have gone dark. Take Magma through them, recover their cores, and bring each one home. With all four connected, we can reach the Singularity without triggering the Great Reset.\n\nThe north breach opens your expedition routes. You can rest here, spend salvage at the anvil, and reconfigure your guardian at the core socket.", "lore_title": "Felix / A world worth keeping", "spawn": [0, 0.1, 8]},
	"field-locker": {"id": "field-locker", "name": "Field Locker", "zone": "outer", "role": "shelter", "layout": "shelter", "exits": [{"to": "forge", "at": [0, 0, 10], "label": "Return to the Forge"}, {"to": "signal-approach", "at": [0, 0, -10], "label": "Explore Signal Approach"}], "enemies": [], "relays": [], "hazards": [], "lore": "The outside relays still remember the Forge. Reconnect the failing span and reclaim its thermal core.\n\nFelix: The Sentinel closes its shield. Let it slam, then punish its recovery.", "lore_title": "Outer Grid / Field note", "spawn": [0, 0.1, 8]},
	"signal-approach": {"id": "signal-approach", "name": "Signal Approach", "zone": "outer", "role": "path", "layout": "foundry-path", "exits": [{"to": "field-locker", "at": [0, 0, 10], "label": "Back to shelter"}, {"to": "firewall-span", "at": [0, 0, -22], "label": "Continue to Firewall Span", "clear": true}], "enemies": [{"id": "outer-patrol", "name": "Damaged Sentinel", "at": [0, 0.1, -5], "hp": 65, "damage": 14, "boss": false, "shield": false, "patterns": ["slam"], "archetype": "bruiser", "salvage": 18}], "relays": [], "hazards": [], "lore": "We left a supply locker beneath the span. The short route goes north. The patient route finds what everyone else abandoned.", "lore_title": "Maintenance log 1", "spawn": [0, 0.1, 8]},
	"firewall-span": {"id": "firewall-span", "name": "Firewall Span", "zone": "outer", "role": "gate", "layout": "foundry-gate", "exits": [{"to": "signal-approach", "at": [0, 0, 10], "label": "Back to approach"}, {"to": "overflow-vent", "at": [0, 0, -22], "label": "Enter Overflow Vent", "clear": true, "power": true}, {"to": "maintenance-cache", "at": [-10, 0, -14], "label": "Search the side passage", "clear": true}], "enemies": [{"id": "outer-guardian", "name": "Span Sentinel", "at": [0, 0.1, -7], "hp": 115, "damage": 20, "boss": false, "shield": true, "patterns": ["slam"], "archetype": "bulwark", "salvage": 28}], "relays": [{"id": "outer-relay-a", "at": [-6, 0, -4]}], "hazards": [], "lore": "These relays respond to heat, not force. Aim Magma Breath into each marked conductor. Two timely hits charge one relay. The bridge remembers a completed circuit even after you return home.", "lore_title": "A circuit still listens", "spawn": [0, 0.1, 8]},
	"maintenance-cache": {"id": "maintenance-cache", "name": "Maintenance Cache", "zone": "outer", "role": "cache", "layout": "cache", "exits": [{"to": "firewall-span", "at": [0, 0, 10], "label": "Return to the junction"}], "enemies": [], "relays": [], "hazards": [], "lore": "The locker is dented, not empty. Inside: spare shielding, a few clean cores, and a note.\n\n“Leave the lantern on. Someone always comes back.”", "lore_title": "The lantern left on", "spawn": [0, 0.1, 8], "reward": 40},
	"overflow-vent": {"id": "overflow-vent", "name": "Overflow Vent", "zone": "outer", "role": "boss", "layout": "foundry-boss", "exits": [{"to": "firewall-span", "at": [0, 0, 10], "label": "Back to junction"}, {"to": "forge", "at": [0, 0, -22], "label": "Carry the core home", "clear": true, "core": true}], "enemies": [{"id": "outer-boss", "name": "Buffer Overflow", "at": [0, 0.1, -13], "hp": 240, "damage": 26, "boss": true, "shield": true, "patterns": ["slam", "ring"], "salvage": 60}], "relays": [], "hazards": [], "lore": "The Sentinel closes its shield. Let it slam, then punish its recovery.", "lore_title": "Buffer Overflow", "spawn": [0, 0.1, 8]},
	"cold-archive": {"id": "cold-archive", "name": "Cold Archive", "zone": "frozen", "role": "shelter", "layout": "shelter", "exits": [{"to": "forge", "at": [0, 0, 10], "label": "Return to the Forge"}, {"to": "mute-channel", "at": [0, 0, -10], "label": "Explore Mute Channel"}], "enemies": [], "relays": [], "hazards": [], "lore": "Memories were frozen to keep them safe. Now the ice is erasing the people inside them. Bring the archive back online.\n\nFelix: The beam locks its direction before firing. Move sideways, not down its length.", "lore_title": "Frozen Cache / Field note", "spawn": [0, 0.1, 8]},
	"mute-channel": {"id": "mute-channel", "name": "Mute Channel", "zone": "frozen", "role": "path", "layout": "ice-path", "exits": [{"to": "cold-archive", "at": [0, 0, 10], "label": "Back to shelter"}, {"to": "thaw-junction", "at": [0, 0, -22], "label": "Continue to Thaw Junction", "clear": true}], "enemies": [{"id": "frozen-patrol", "name": "Archive Sentry", "at": [0, 0.1, -5], "hp": 80, "damage": 16, "boss": false, "shield": false, "patterns": ["beam"], "archetype": "sniper", "salvage": 20}], "relays": [], "hazards": [{"at": [0, 0, -14], "radius": 2.4, "period": 5.0, "warning": 1.6, "damage": 12, "offset": 0.8}], "lore": "Do not follow the beam. It is not pointing toward an exit. Cut across its path after it locks, and the archive guardian will need time to recover.", "lore_title": "Maintenance log 2", "spawn": [0, 0.1, 8]},
	"thaw-junction": {"id": "thaw-junction", "name": "Thaw Junction", "zone": "frozen", "role": "gate", "layout": "ice-gate", "exits": [{"to": "mute-channel", "at": [0, 0, 10], "label": "Back to approach"}, {"to": "memory-vault", "at": [0, 0, -22], "label": "Enter Memory Vault", "clear": true, "power": true}, {"to": "frozen-vault", "at": [-10, 0, -14], "label": "Search the side passage", "clear": true}], "enemies": [{"id": "frozen-guardian", "name": "Thaw Guardian", "at": [0, 0.1, -7], "hp": 130, "damage": 22, "boss": false, "shield": true, "patterns": ["beam", "slam"], "archetype": "sniper", "salvage": 31}], "relays": [{"id": "frozen-relay-a", "at": [-6, 0, -4]}, {"id": "frozen-relay-b", "at": [6, 0, -12]}], "hazards": [], "lore": "These relays respond to heat, not force. Aim Magma Breath into each marked conductor. Two timely hits charge one relay. The bridge remembers a completed circuit even after you return home.", "lore_title": "A circuit still listens", "spawn": [0, 0.1, 8]},
	"frozen-vault": {"id": "frozen-vault", "name": "Frozen Vault", "zone": "frozen", "role": "cache", "layout": "cache", "exits": [{"to": "thaw-junction", "at": [0, 0, 10], "label": "Return to the junction"}], "enemies": [], "relays": [], "hazards": [], "lore": "Someone preserved these memories without knowing whether anyone would return for them.\n\nA faceted guardian egg still has a heartbeat. Rescue it from the cyan incubator and hatch it at the Forge. Ice can slow exposed enemies; Magma can shatter that chill.\n\nYou carry the record back to the Forge. The person it remembers is no longer completely lost.", "lore_title": "Cold keeps what fire forgets", "spawn": [0, 0.1, 8], "reward": 45},
	"memory-vault": {"id": "memory-vault", "name": "Memory Vault", "zone": "frozen", "role": "boss", "layout": "ice-boss", "exits": [{"to": "thaw-junction", "at": [0, 0, 10], "label": "Back to junction"}, {"to": "forge", "at": [0, 0, -22], "label": "Carry the core home", "clear": true, "core": true}], "enemies": [{"id": "frozen-boss", "name": "Memory Leak", "at": [0, 0.1, -13], "hp": 305, "damage": 29, "boss": true, "shield": true, "patterns": ["beam", "slam"], "salvage": 70}], "relays": [], "hazards": [], "lore": "The beam locks its direction before firing. Move sideways, not down its length.", "lore_title": "Memory Leak", "spawn": [0, 0.1, 8]},
	"overclock-gantry": {"id": "overclock-gantry", "name": "Overclock Gantry", "zone": "storm", "role": "shelter", "layout": "shelter", "exits": [{"to": "forge", "at": [0, 0, 10], "label": "Return to the Forge"}, {"to": "live-wire", "at": [0, 0, -10], "label": "Explore Live Wire"}], "enemies": [], "relays": [], "hazards": [], "lore": "The spine is overclocking itself to death. Reroute the conductors, then quiet the process driving the surge.\n\nFelix: Gold circles mark three separate impacts. Find the gap before they discharge.", "lore_title": "Storm Spine / Field note", "spawn": [0, 0.1, 8]},
	"live-wire": {"id": "live-wire", "name": "Live Wire", "zone": "storm", "role": "path", "layout": "storm-path", "exits": [{"to": "overclock-gantry", "at": [0, 0, 10], "label": "Back to shelter"}, {"to": "wire-fork", "at": [0, 0, -22], "label": "Continue to Wire Fork", "clear": true}], "enemies": [{"id": "storm-patrol", "name": "Surge Sentry", "at": [0, 0.1, -5], "hp": 95, "damage": 18, "boss": false, "shield": false, "patterns": ["fan"], "archetype": "skirmisher", "salvage": 22}], "relays": [], "hazards": [{"at": [0, 0, -14], "radius": 2.4, "period": 5.0, "warning": 1.6, "damage": 12, "offset": 0.8}], "lore": "The gold lines are warnings, not walls. Let the discharge pass. We used to walk this gantry by listening to the gaps.", "lore_title": "Maintenance log 3", "spawn": [0, 0.1, 8]},
	"wire-fork": {"id": "wire-fork", "name": "Wire Fork", "zone": "storm", "role": "gate", "layout": "storm-gate", "exits": [{"to": "live-wire", "at": [0, 0, 10], "label": "Back to approach"}, {"to": "logic-core", "at": [0, 0, -22], "label": "Enter Logic Core", "clear": true, "power": true}, {"to": "capacitor-cache", "at": [-10, 0, -14], "label": "Search the side passage", "clear": true}], "enemies": [{"id": "storm-guardian", "name": "Fork Guardian", "at": [0, 0.1, -7], "hp": 145, "damage": 24, "boss": false, "shield": true, "patterns": ["fan", "slam"], "archetype": "skirmisher", "salvage": 34}], "relays": [{"id": "storm-relay-a", "at": [-6, 0, -4]}, {"id": "storm-relay-b", "at": [6, 0, -12]}], "hazards": [], "lore": "These relays respond to heat, not force. Aim Magma Breath into each marked conductor. Two timely hits charge one relay. The bridge remembers a completed circuit even after you return home.", "lore_title": "A circuit still listens", "spawn": [0, 0.1, 8]},
	"capacitor-cache": {"id": "capacitor-cache", "name": "Capacitor Cache", "zone": "storm", "role": "cache", "layout": "cache", "exits": [{"to": "wire-fork", "at": [0, 0, 10], "label": "Return to the junction"}], "enemies": [], "relays": [], "hazards": [], "lore": "In a silent alcove beside the live wire, an engineer kept a list of things to repair after the storm. The list has no final entry.", "lore_title": "A pocket of quiet", "spawn": [0, 0.1, 8], "reward": 50},
	"logic-core": {"id": "logic-core", "name": "Logic Core", "zone": "storm", "role": "boss", "layout": "storm-boss", "exits": [{"to": "wire-fork", "at": [0, 0, 10], "label": "Back to junction"}, {"to": "forge", "at": [0, 0, -22], "label": "Carry the core home", "clear": true, "core": true}], "enemies": [{"id": "storm-boss", "name": "Stack Overflow", "at": [0, 0.1, -13], "hp": 370, "damage": 32, "boss": true, "shield": true, "patterns": ["fan", "beam"], "salvage": 80}], "relays": [], "hazards": [], "lore": "Gold circles mark three separate impacts. Find the gap before they discharge.", "lore_title": "Stack Overflow", "spawn": [0, 0.1, 8]},
	"mirror-vestibule": {"id": "mirror-vestibule", "name": "Mirror Vestibule", "zone": "admin", "role": "shelter", "layout": "shelter", "exits": [{"to": "forge", "at": [0, 0, 10], "label": "Return to the Forge"}, {"to": "recursive-gate", "at": [0, 0, -10], "label": "Explore Recursive Gate"}], "enemies": [], "relays": [], "hazards": [], "lore": "The administrator calls it a reset. Felix calls it forgetting everyone. Wake the cold lanterns and take back the last core.\n\nFelix: A ring attack has a safe center. Get close or leave the whole marked ring.", "lore_title": "Admin Core / Field note", "spawn": [0, 0.1, 8]},
	"recursive-gate": {"id": "recursive-gate", "name": "Recursive Gate", "zone": "admin", "role": "path", "layout": "void-path", "exits": [{"to": "mirror-vestibule", "at": [0, 0, 10], "label": "Back to shelter"}, {"to": "cold-lanterns", "at": [0, 0, -22], "label": "Continue to Cold Lanterns", "clear": true}], "enemies": [{"id": "admin-patrol", "name": "Protocol Sentry", "at": [0, 0.1, -5], "hp": 110, "damage": 20, "boss": false, "shield": false, "patterns": ["ring"], "archetype": "controller", "salvage": 24}], "relays": [], "hazards": [{"at": [0, 0, -14], "radius": 2.4, "period": 5.0, "warning": 1.6, "damage": 12, "offset": 0.8}], "lore": "Every reset begins with a clean ledger. Someone has to decide which names deserve to stay. This time, it will not be the administrator.", "lore_title": "Maintenance log 4", "spawn": [0, 0.1, 8]},
	"cold-lanterns": {"id": "cold-lanterns", "name": "Cold Lanterns", "zone": "admin", "role": "gate", "layout": "void-gate", "exits": [{"to": "recursive-gate", "at": [0, 0, 10], "label": "Back to approach"}, {"to": "protocol-throne", "at": [0, 0, -22], "label": "Enter Protocol Throne", "clear": true, "power": true}, {"to": "admin-vault", "at": [-10, 0, -14], "label": "Search the side passage", "clear": true}], "enemies": [{"id": "admin-guardian", "name": "Recursive Guardian", "at": [0, 0.1, -7], "hp": 160, "damage": 26, "boss": false, "shield": true, "patterns": ["ring", "beam"], "archetype": "controller", "salvage": 37}], "relays": [{"id": "admin-relay-a", "at": [-6, 0, -4]}, {"id": "admin-relay-b", "at": [6, 0, -12]}], "hazards": [], "lore": "These relays respond to heat, not force. Aim Magma Breath into each marked conductor. Two timely hits charge one relay. The bridge remembers a completed circuit even after you return home.", "lore_title": "A circuit still listens", "spawn": [0, 0.1, 8]},
	"admin-vault": {"id": "admin-vault", "name": "Admin Vault", "zone": "admin", "role": "cache", "layout": "cache", "exits": [{"to": "cold-lanterns", "at": [0, 0, 10], "label": "Return to the junction"}], "enemies": [], "relays": [], "hazards": [], "lore": "The administrator kept an exception list. Not everyone was supposed to vanish. Felix’s name was there. Yours was not.", "lore_title": "The names that remained", "spawn": [0, 0.1, 8], "reward": 55},
	"protocol-throne": {"id": "protocol-throne", "name": "Protocol Throne", "zone": "admin", "role": "boss", "layout": "void-boss", "exits": [{"to": "cold-lanterns", "at": [0, 0, 10], "label": "Back to junction"}, {"to": "forge", "at": [0, 0, -22], "label": "Carry the core home", "clear": true, "core": true}], "enemies": [{"id": "admin-boss", "name": "Mirror Admin", "at": [0, 0.1, -13], "hp": 435, "damage": 35, "boss": true, "shield": true, "patterns": ["ring", "beam", "fan"], "salvage": 90}], "relays": [], "hazards": [], "lore": "A ring attack has a safe center. Get close or leave the whole marked ring.", "lore_title": "Mirror Admin", "spawn": [0, 0.1, 8]},
	"singularity": {"id": "singularity", "name": "The Singularity", "zone": "final", "role": "final", "layout": "final", "exits": [{"to": "forge", "at": [0, 0, 10], "label": "Return to the Forge"}], "enemies": [{"id": "singularity-final", "name": "The Singularity", "at": [0, 0.1, -13], "hp": 620, "damage": 36, "boss": true, "shield": true, "patterns": ["beam", "fan", "ring"], "salvage": 100}], "relays": [], "hazards": [], "lore": "Felix: All four sectors are speaking again. The Singularity is listening. Break its reset cycle, then reconnect the heart. No one has to disappear for the world to continue.", "lore_title": "No Great Reset", "spawn": [0, 0.1, 8]}
}

static func v3(value: Array) -> Vector3:
	return Vector3(float(value[0]), float(value[1]), float(value[2]))

static func zone(id: String) -> Dictionary:
	for item in ZONES:
		if item.id == id:
			return item
	return {"id": id, "name": "The Forge" if id == "home" else "The Singularity", "color": "f0b572" if id == "home" else "ad98ff", "theme": "foundry" if id == "home" else "void"}

static func encounter_ids() -> Array:
	var result: Array = []
	for r in ROOMS.values():
		for e in r.enemies:
			result.append(e.id)
	return result

static func relay_ids() -> Array:
	var result: Array = []
	for r in ROOMS.values():
		for relay in r.relays:
			result.append(relay.id)
	return result

static func room_cleared(state: Dictionary, id: String) -> bool:
	for foe in ROOMS[id].enemies:
		if not state.cleared.has(foe.id):
			return false
	return true

static func room_powered(state: Dictionary, id: String) -> bool:
	for relay in ROOMS[id].relays:
		if not state.relays.has(relay.id):
			return false
	return true

static func zone_unlocked(state: Dictionary, id: String) -> bool:
	if id == "home":
		return true
	if not state.hatched:
		return false
	if id == "final":
		return state.installed.size() == 4
	for i in range(ZONES.size()):
		if ZONES[i].id == id:
			return i == 0 or state.installed.has(ZONES[i-1].id)
	return false

static func exit_reason(state: Dictionary, from: String, exit: Dictionary) -> String:
	if exit.get("clear", false) and not room_cleared(state, from):
		return "Defeat the guardians first"
	if exit.get("power", false) and not room_powered(state, from):
		return "Charge every relay with Magma Breath"
	if exit.get("core", false) and not state.cores.has(ROOMS[from].zone):
		return "Collect the core from the pedestal"
	if not zone_unlocked(state, ROOMS[exit.to].zone):
		return "Restore the preceding sector at the Forge"
	return ""
